version: '3.8'

services:
  # Main application service
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - PORT=8000
      - ENVIRONMENT=development
    env_file:
      - .env
    volumes:
      # Mount source code for development hot-reloading
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - redis
    networks:
      - youtube-summarizer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - youtube-summarizer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Development tools service
  dev-tools:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
    env_file:
      - .env
    networks:
      - youtube-summarizer-network
    profiles:
      - dev
    depends_on:
      - redis

networks:
  youtube-summarizer-network:
    driver: bridge

volumes:
  redis_data:
    driver: local